package com.magmaguy.freeminecraftmodels.animation;

import com.google.gson.Gson;
import com.magmaguy.freeminecraftmodels.MetadataHandler;
import com.magmaguy.freeminecraftmodels.customentity.ModeledEntity;
import com.magmaguy.freeminecraftmodels.customentity.core.Bone;
import com.magmaguy.freeminecraftmodels.customentity.core.components.AnimationComponent;
import com.magmaguy.freeminecraftmodels.dataconverter.FileModelConverter;
import org.bukkit.Location;
import org.bukkit.plugin.Plugin;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.lang.reflect.Proxy;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AnimationPlaybackTest {
    private static final String ROOT = "freeminecraftmodels_autogenerated_root";
    @TempDir Path directory;
    private Plugin previousPlugin;
    private AnimationComponent animation;
    private Bone bone;

    @BeforeEach
    void loadProductionModel() throws Exception {
        previousPlugin = MetadataHandler.PLUGIN;
        // Only the external Bukkit plugin identity is needed to construct NamespacedKeys.
        MetadataHandler.PLUGIN = (Plugin) Proxy.newProxyInstance(Plugin.class.getClassLoader(),
                new Class<?>[]{Plugin.class}, (proxy, method, args) -> {
                    if (method.getName().equals("getName")) return "FreeMinecraftModels";
                    throw new UnsupportedOperationException(method.getName());
                });
        Path source = directory.resolve("animation_playback.bbmodel");
        Files.writeString(source, new Gson().toJson(Map.of(
                "meta", Map.of("format_version", "4.0"), "outliner", List.of(), "elements", List.of(),
                "animations", List.of(
                        track("idle", frame("position", 0, 0)),
                        track("sweep", frame("position", 0, 0), frame("position", 0.2, 64)),
                        track("pose", frame("position", 0, 64), frame("rotation", 0, 90), frame("scale", 0, 2))))));
        FileModelConverter converter = new FileModelConverter(source.toFile());
        ModeledEntity model = new ModeledEntity(converter.getID(), new Location(null, 0, 0, 0));
        animation = model.getAnimationComponent();
        bone = model.getSkeleton().getBoneMap().get(ROOT);
    }

    @AfterEach
    void discardModel() {
        FileModelConverter.shutdown();
        MetadataHandler.PLUGIN = previousPlugin;
    }

    @Test
    void playReplacementAndStopApplyActualBonePoses() {
        assertTrue(animation.playAnimation("sweep", false, true));
        animation.tick();
        assertEquals(0, bone.getAnimationTranslation().x, 0.00001);
        animation.tick();
        assertEquals(1, bone.getAnimationTranslation().x, 0.00001);
        assertFalse(animation.playAnimation("unknown", false, false));
        animation.tick();
        assertEquals(2, bone.getAnimationTranslation().x, 0.00001, "Rejected animation must leave playback running");

        assertTrue(animation.playAnimation("pose", false, true));
        animation.tick();
        assertEquals(4, bone.getAnimationTranslation().x, 0.00001);
        assertEquals(Math.PI / 2, bone.getAnimationRotation().x, 0.00001);
        assertEquals(2, bone.getAnimationScale().x, 0.00001);
        animation.stopCurrentAnimations();
        animation.tick();
        assertEquals(0, bone.getAnimationTranslation().x, 0.00001);
        assertEquals(0, bone.getAnimationRotation().x, 0.00001);
        assertEquals(1, bone.getAnimationScale().x, 0.00001);
    }

    @Test
    void loopWrapsAndOneShotReturnsToIdle() {
        assertTrue(animation.playAnimation("sweep", false, true));
        for (int tick = 0; tick < 5; tick++) animation.tick();
        assertEquals(0, bone.getAnimationTranslation().x, 0.00001, "The fifth tick wraps the four-frame loop");
        animation.tick();
        assertEquals(1, bone.getAnimationTranslation().x, 0.00001);
        assertTrue(animation.playAnimation("sweep", false, false));
        for (int tick = 0; tick < 4; tick++) animation.tick();
        assertEquals(3, bone.getAnimationTranslation().x, 0.00001, "A new play starts at the first frame");
        animation.tick();
        animation.tick();
        assertEquals(0, bone.getAnimationTranslation().x, 0.00001, "The completed one-shot returns to idle");
    }

    private static Map<String, Object> track(String name, Object... keyframes) {
        return Map.of("name", name, "loop", "loop", "length", 0.2,
                "animators", Map.of("root", Map.of("name", ROOT, "type", "bone", "keyframes", List.of(keyframes))));
    }

    private static Map<String, Object> frame(String channel, double time, double x) {
        double other = channel.equals("scale") ? 1 : 0;
        return Map.of("channel", channel, "interpolation", "linear", "time", time,
                "data_points", List.of(Map.of("x", x, "y", other, "z", other)));
    }
}
